version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-user-1
      - backend-user-2
      - backend-user-3
      - backend-admin-1
      - backend-admin-2
      - backend-admin-3
    networks:
      - app-network

  backend-user-1:
    build: ./backend-user
    environment:
      - NODE_ENV=production
    volumes:
      - ./products.json:/app/products.json
    networks:
      - app-network

  backend-user-2:
    build: ./backend-user
    environment:
      - NODE_ENV=production
    volumes:
      - ./products.json:/app/products.json
    networks:
      - app-network

  backend-user-3:
    build: ./backend-user
    environment:
      - NODE_ENV=production
    volumes:
      - ./products.json:/app/products.json
    networks:
      - app-network

  backend-admin-1:
    build: ./backend-admin
    environment:
      - NODE_ENV=production
    volumes:
      - ./products.json:/app/products.json
    networks:
      - app-network

  backend-admin-2:
    build: ./backend-admin
    environment:
      - NODE_ENV=production
    volumes:
      - ./products.json:/app/products.json
    networks:
      - app-network

  backend-admin-3:
    build: ./backend-admin
    environment:
      - NODE_ENV=production
    volumes:
      - ./products.json:/app/products.json
    networks:
      - app-network

  frontend-user:
    build: ./frontend-user
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost/graphql
      - REACT_APP_WS_URL=ws://localhost/ws
    depends_on:
      - nginx
    networks:
      - app-network

  frontend-admin:
    build: ./frontend-admin
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost/api
      - REACT_APP_WS_URL=ws://localhost/ws
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 